package com.programa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-01-14T15:57:18.999-05:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://programa.com", name = "SOATestEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SOATestEndpoint {

    @WebMethod(operationName = "SOATest", action = "http://programa.com")
    @WebResult(name = "outputSOATest", targetNamespace = "http://programa.com", partName = "out")
    public OutputSOATest soaTest(

        @WebParam(partName = "in", name = "inputSOATest", targetNamespace = "http://programa.com")
        InputSOATest in
    );
}
